service: healthbot-frontend

frameworkVersion: '~4.14.3'

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: healthbot-frontend-dev
      localDir: frontend/build

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: healthbot-frontend-dev
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicRead
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: arn:aws:s3:::healthbot-frontend-dev/*