service: healthbot-backend

frameworkVersion: '^3.38.0'

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  stage: dev
  environment:
    CHAT_SESSIONS_TABLE: ${self:service}-chat-sessions-${self:provider.stage}
    USER_MESSAGES_TABLE: ${self:service}-user-messages-${self:provider.stage}
    SESSION_STATE_TABLE: healthbot-backend-session-state-v2-${self:provider.stage}
    SECRETS_NAME: ${self:service}-secrets-${self:provider.stage}
    OPENAI_BASE_URL: https://openai.vocareum.com/v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt ChatSessionsTable.Arn
            - !GetAtt UserMessagesTable.Arn
            - !GetAtt SessionStateTable.Arn
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt SessionStateTable.Arn
            - !Sub "${SessionStateTable.Arn}/*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
          Resource:
            - "arn:aws:secretsmanager:us-east-1:*:secret:healthbot-backend-secrets-*"

functions:
  processUserMessage:
    handler: src/handlers/process_user_message.handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/api-gateway.yml)}
  - ${file(resources/cognito.yml)}