service: healthbot-backend

frameworkVersion: '^3.38.0'

provider:
  name: aws
  region: us-east-1
  runtime: python3.11
  stage: dev
  environment:
    CHAT_SESSIONS_TABLE: ${self:service}-chat-sessions-${self:provider.stage}
    USER_MESSAGES_TABLE: ${self:service}-user-messages-${self:provider.stage}
    SESSION_STATE_TABLE: !Ref SessionStateTable
    SECRETS_NAME: ${self:service}-secrets-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt ChatSessionsTable.Arn
            - !GetAtt UserMessagesTable.Arn
            - !GetAtt SessionStateTable.Arn
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
          Resource:
            - "arn:aws:secretsmanager:us-east-1:*:secret:healthbot-backend-secrets-*"

functions:
  processUserMessage:
    handler: src/handlers/process_user_message.handler
    events:
      - http:
          path: api/messages
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref CognitoUserPoolAuthorizer

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/cognito.yml)}
  
  # API Gateway Authorizer
  CognitoUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: cognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGatewayRestApi
      ProviderARNs:
        - !GetAtt CognitoUserPool.Arn