Resources:
  HealthBotSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-secrets-${self:provider.stage}
      Description: Secrets for HealthBot backend including API keys
      SecretString: '{"OPENAI_API_KEY":"","TAVILY_API_KEY":""}'

Outputs:
  HealthBotSecretsArn:
    Description: ARN of the HealthBot secrets
    Value:
      Ref: HealthBotSecrets
    Export:
      Name: ${self:service}-SecretsArn-${self:provider.stage}
